/**
* Generated by unionj-generator.
* You can edit it as your need.
*/
import { responseUse } from "@/utils/response";

export class BizService {

  static serverName: string | undefined = process.env.VUE_APP_BIZ_SERVICE;

  axios: any;

  constructor(axios: any) {
    this.axios = axios;
    this.axios.interceptors.response.use(responseUse,null);
  }

  protected addPrefix(endpoint: string){
    if(BizService.serverName) {
      if(BizService.serverName.indexOf("/") === 0 || BizService.serverName.indexOf("http") === 0) {
        return BizService.serverName + endpoint
      }
      return "/" + BizService.serverName + endpoint
    }
    return endpoint
  }

}

export default BizService;
