/**
* Generated by unionj-generator.
* Don't edit!
* @module types
*/

export interface ResultVO {
    code: number;
    msg: string;
    data: any;
}


/**
* 用户注册结果
*/
export interface UserRegisterRespVO {
    /**
    * 用户ID
    */
    id: string;
}


export interface ResultVOUserRegisterRespVO {
    code: number;
    msg: string;
    data: UserRegisterRespVO;
}


export interface ResultVOUserDetailVO {
    code: number;
    msg: string;
    data: UserDetailVO;
}


/**
* 用户信息编辑表单
*/
export interface UserEditFormVO {
    /**
    * 真实姓名
    */
    name: string;
    /**
    * 年龄
    */
    age: number;
    /**
    * 性别
    */
    sex: UserEditFormVOSexEnum;
    /**
    * 用户头像
    */
    avatar: Blob;
}

export enum UserEditFormVOSexEnum {
    BOY = "BOY",
    GIRL = "GIRL",
}

export interface ResultVOString {
    code: number;
    msg: string;
    data: string;
}


export interface PageResultVO {
    items: any[];
    /**
    * 总数
    */
    total: number;
    /**
    * 每页多少条数据
    */
    size: number;
    /**
    * 当前页码
    */
    current: number;
    /**
    * 总页数
    */
    pages: number;
}


/**
* 用户列表分页查询条件
*/
export interface UserPageReqVO {
    /**
    * 每页多少条数据
    */
    size: number;
    /**
    * 第几页
    */
    current: number;
    /**
    * 排序条件字符串：排序字段前使用'-'(降序)和'+'(升序)号表示排序规则，多个排序字段用','隔开
    */
    sort: string;
    /**
    * 筛选条件：用户性别
    */
    sex: string;
}


/**
* 用户注册表单
*/
export interface UserRegisterFormVO {
    /**
    * 用户名
    */
    username: string;
    /**
    * 密码
    */
    password: string;
}


export interface PageResultVOUserDetailVO {
    items: UserDetailVO[];
    /**
    * 总数
    */
    total: number;
    /**
    * 每页多少条数据
    */
    size: number;
    /**
    * 当前页码
    */
    current: number;
    /**
    * 总页数
    */
    pages: number;
}


export interface ResultVOPageResultVOUserDetailVO {
    code: number;
    msg: string;
    data: PageResultVOUserDetailVO;
}


/**
* 用户详情
*/
export interface UserDetailVO {
    /**
    * 用户ID
    */
    id: string;
    /**
    * 真实姓名
    */
    name: string;
    /**
    * 年龄
    */
    age: number;
    /**
    * 性别
    */
    sex: UserDetailVOSexEnum;
    /**
    * 用户头像下载地址
    */
    avatar: string;
}

export enum UserDetailVOSexEnum {
    BOY = "BOY",
    GIRL = "GIRL",
}

